import { app, dialog } from 'electron';
import { requireBackendModule } from '../utils/backend-loader';
import { getBackendApp, setBackendApp } from '../state';

export let generateReportTemplate: (...args: any[]) => any;
export let initializeBackend: (userDataPath?: string) => Promise<any>;
export let shutdownBackend: () => Promise<void>;
export let healthGetHealth: () => Promise<any>;
export let usersFindAll: () => Promise<any>;
export let usersFindOne: (...args: any[]) => Promise<any>;
export let usersFindByUsername: (...args: any[]) => Promise<any>;
export let usersCreate: (...args: any[]) => Promise<any>;
export let usersUpdate: (...args: any[]) => Promise<any>;
export let usersRemove: (...args: any[]) => Promise<any>;
export let authLogin: (...args: any[]) => Promise<any>;
export let authGetMe: (...args: any[]) => Promise<any>;
export let authVerifyPassword: (...args: any[]) => Promise<any>;
export let itemsFindAll: (...args: any[]) => Promise<any>;
export let itemsFindOne: (...args: any[]) => Promise<any>;
export let itemsCreate: (...args: any[]) => Promise<any>;
export let itemsUpdate: (...args: any[]) => Promise<any>;
export let itemsRemove: (...args: any[]) => Promise<any>;
export let uploadSaveFile: (...args: any[]) => Promise<any>;
export let categoriesFindAll: () => Promise<any>;
export let categoriesFindOne: (...args: any[]) => Promise<any>;
export let categoriesCreate: (...args: any[]) => Promise<any>;
export let categoriesUpdate: (...args: any[]) => Promise<any>;
export let categoriesRemove: (...args: any[]) => Promise<any>;
export let categoriesReorder: (...args: any[]) => Promise<any>;
export let ordersFindByTable: (...args: any[]) => Promise<any>;
export let ordersFindByHall: (...args: any[]) => Promise<any>;
export let ordersFindActiveOrders: () => Promise<any>;
export let ordersCreate: (...args: any[]) => Promise<any>;
export let ordersUpdate: (...args: any[]) => Promise<any>;
export let ordersUpdateStatus: (...args: any[]) => Promise<any>;
export let ordersRemove: (...args: any[]) => Promise<any>;
export let dineInOrdersCreate: (...args: any[]) => Promise<any>;
export let dineInOrdersFindActive: () => Promise<any>;
export let dineInOrdersFindArchived: () => Promise<any>;
export let dineInOrdersFindById: (...args: any[]) => Promise<any>;
export let dineInOrdersFindByTable: (...args: any[]) => Promise<any>;
export let dineInOrdersFindByHall: (...args: any[]) => Promise<any>;
export let dineInOrdersUpdate: (...args: any[]) => Promise<any>;
export let dineInOrdersUpdateStatus: (...args: any[]) => Promise<any>;
export let dineInOrdersMoveTableOrders: (...args: any[]) => Promise<any>;
export let dineInOrdersMoveOrders: (...args: any[]) => Promise<any>;
export let dineInOrdersSetTableGlobalDiscount: (...args: any[]) => Promise<any>;
export let dineInOrdersRemoveAllArchived: () => Promise<any>;
export let pickupOrdersFindActive: () => Promise<any>;
export let pickupOrdersFindArchived: () => Promise<any>;
export let pickupOrdersFindById: (...args: any[]) => Promise<any>;
export let pickupOrdersCreate: (...args: any[]) => Promise<any>;
export let pickupOrdersUpdate: (...args: any[]) => Promise<any>;
export let pickupOrdersUpdateStatus: (...args: any[]) => Promise<any>;
export let pickupOrdersRemove: (...args: any[]) => Promise<any>;
export let pickupOrdersRemoveAllArchived: () => Promise<any>;
export let deliveryOrdersFindActive: () => Promise<any>;
export let deliveryOrdersFindArchived: () => Promise<any>;
export let deliveryOrdersFindById: (...args: any[]) => Promise<any>;
export let deliveryOrdersCreate: (...args: any[]) => Promise<any>;
export let deliveryOrdersUpdate: (...args: any[]) => Promise<any>;
export let deliveryOrdersUpdateStatus: (...args: any[]) => Promise<any>;
export let deliveryOrdersRemove: (...args: any[]) => Promise<any>;
export let deliveryOrdersRemoveAllArchived: () => Promise<any>;
export let deliveryPlatformsFindAll: () => Promise<any>;
export let deliveryPlatformsCreate: (...args: any[]) => Promise<any>;
export let deliveryPlatformsUpdate: (...args: any[]) => Promise<any>;
export let deliveryPlatformsRemove: (...args: any[]) => Promise<any>;
export let tablesFindAll: () => Promise<any>;
export let tablesFindByHall: (...args: any[]) => Promise<any>;
export let tablesFindOne: (...args: any[]) => Promise<any>;
export let tablesCreate: (...args: any[]) => Promise<any>;
export let tablesUpdate: (...args: any[]) => Promise<any>;
export let tablesRemove: (...args: any[]) => Promise<any>;
export let hallsFindAll: () => Promise<any>;
export let hallsFindOne: (...args: any[]) => Promise<any>;
export let hallsCreate: (...args: any[]) => Promise<any>;
export let hallsUpdate: (...args: any[]) => Promise<any>;
export let hallsRemove: (...args: any[]) => Promise<any>;
export let floorsFindAll: () => Promise<any>;
export let floorsFindOne: (...args: any[]) => Promise<any>;
export let floorsCreate: (...args: any[]) => Promise<any>;
export let floorsUpdate: (...args: any[]) => Promise<any>;
export let floorsRemove: (...args: any[]) => Promise<any>;
export let kitchensFindAll: () => Promise<any>;
export let kitchensFindOne: (...args: any[]) => Promise<any>;
export let kitchensCreate: (...args: any[]) => Promise<any>;
export let kitchensUpdate: (...args: any[]) => Promise<any>;
export let kitchensRemove: (...args: any[]) => Promise<any>;
export let printersGetAllSettings: () => Promise<any>;
export let printersGetAvailablePrinters: () => Promise<any>;
export let printersSaveSetting: (...args: any[]) => Promise<any>;
export let printersDeleteSetting: (...args: any[]) => Promise<any>;
export let offersCreateDailyDeal: (...args: any[]) => Promise<any>;
export let offersGetAllDailyDeals: () => Promise<any>;
export let offersGetActiveDailyDeal: () => Promise<any>;
export let offersGetDailyDealByDate: (...args: any[]) => Promise<any>;
export let offersUpdateDailyDeal: (...args: any[]) => Promise<any>;
export let offersDeleteDailyDeal: (...args: any[]) => Promise<any>;
export let offersCreateCombo: (...args: any[]) => Promise<any>;
export let offersGetAllCombos: () => Promise<any>;
export let offersGetCombo: (...args: any[]) => Promise<any>;
export let offersUpdateCombo: (...args: any[]) => Promise<any>;
export let offersDeleteCombo: (...args: any[]) => Promise<any>;
export let offersCreateScheduledOffer: (...args: any[]) => Promise<any>;
export let offersGetAllScheduledOffers: () => Promise<any>;
export let offersGetActiveScheduledOffers: () => Promise<any>;
export let offersGetScheduledOffer: (...args: any[]) => Promise<any>;
export let offersUpdateScheduledOffer: (...args: any[]) => Promise<any>;
export let offersDeleteScheduledOffer: (...args: any[]) => Promise<any>;
export let offersSetFeatured: (...args: any[]) => Promise<any>;
export let offersGetAllFeaturedItems: () => Promise<any>;
export let offersIsFeatured: (...args: any[]) => Promise<any>;
export let offersCreateHappyHour: (...args: any[]) => Promise<any>;
export let offersGetAllHappyHours: () => Promise<any>;
export let offersGetHappyHour: (...args: any[]) => Promise<any>;
export let offersUpdateHappyHour: (...args: any[]) => Promise<any>;
export let offersDeleteHappyHour: (...args: any[]) => Promise<any>;
export let offersGetEffectivePrice: (...args: any[]) => Promise<any>;
export let offersEnrichItemsWithOffers: (...args: any[]) => Promise<any>;
export let getReportsDailySummary: () => Promise<any>;
export let getReportsReportData: (
  period: 'daily' | 'weekly' | 'monthly' | 'yearly',
  date: string,
) => Promise<any>;
export let generateReportsExcel: (dto: unknown) => Promise<Buffer>;
export let shelvesFindAll: () => Promise<any>;
export let shelvesFindOneById: (...args: any[]) => Promise<any>;
export let shelvesFindOneByBarcode: (...args: any[]) => Promise<any>;
export let shelvesCreate: (...args: any[]) => Promise<any>;
export let shelvesUpdate: (...args: any[]) => Promise<any>;
export let shelvesRemove: (...args: any[]) => Promise<any>;
export let shelvesSell: (...args: any[]) => Promise<any>;
export let shiftsGetAllShifts: (...args: any[]) => Promise<any>;
export let shiftsGetActiveShift: () => Promise<any>;
export let shiftsGetShiftById: (...args: any[]) => Promise<any>;
export let shiftsStartShift: (...args: any[]) => Promise<any>;
export let shiftsFinishShift: (...args: any[]) => Promise<any>;
export let financeGetRevenues: (...args: any[]) => Promise<any>;
export let financeCreateRevenue: (...args: any[]) => Promise<any>;
export let financeSyncRevenueFromOrders: (...args: any[]) => Promise<any>;
export let financeGetExpenses: (...args: any[]) => Promise<any>;
export let financeCreateExpense: (...args: any[]) => Promise<any>;
export let financeUpdateExpense: (...args: any[]) => Promise<any>;
export let financeDeleteExpense: (...args: any[]) => Promise<any>;
export let financeGetCashFlow: (...args: any[]) => Promise<any>;
export let financeCreateCashFlow: (...args: any[]) => Promise<any>;
export let financeSyncCashFlowFromOrders: (...args: any[]) => Promise<void>;
export let financeGetProfitAndLoss: (...args: any[]) => Promise<any>;
export let businessDayGetCurrentBusinessDay: () => Promise<any>;
export let businessDayStartNewBusinessDay: (...args: any[]) => Promise<any>;
export let businessDayEnsureBusinessDayExists: () => Promise<any>;
export let businessDayGetAllBusinessDays: () => Promise<any>;
export let settingsGetShiftHours: () => Promise<any>;
export let settingsUpdateShiftHours: (...args: any[]) => Promise<any>;
export let settingsGetShiftDefinitions: () => Promise<any>;
export let settingsCreateShiftDefinition: (...args: any[]) => Promise<any>;
export let settingsUpdateShiftDefinition: (...args: any[]) => Promise<any>;
export let settingsRemoveShiftDefinition: (...args: any[]) => Promise<any>;
export let settingsReplaceShiftDefinitions: (...args: any[]) => Promise<any>;

export function loadBackendModules(): void {
  try {
    console.log('[MAIN] Loading backend modules dynamically...');
    generateReportTemplate = requireBackendModule('modules/reports/generate-report-template').generateReportTemplate;
    const mainModule = requireBackendModule('main');
    initializeBackend = mainModule.initializeBackend;
    shutdownBackend = mainModule.shutdownBackend;
    healthGetHealth = requireBackendModule('modules/health/health.service').getHealth;
    const usersModule = requireBackendModule('modules/users/users.service');
    usersFindAll = usersModule.findAll;
    usersFindOne = usersModule.findOne;
    usersFindByUsername = usersModule.findByUsername;
    usersCreate = usersModule.create;
    usersUpdate = usersModule.update;
    usersRemove = usersModule.remove;
    const authModule = requireBackendModule('modules/auth/auth.service');
    authLogin = authModule.login;
    authGetMe = authModule.getMe;
    authVerifyPassword = authModule.verifyPassword;
    const itemsModule = requireBackendModule('modules/items/items.service');
    itemsFindAll = itemsModule.findAll;
    itemsFindOne = itemsModule.findOne;
    itemsCreate = itemsModule.create;
    itemsUpdate = itemsModule.update;
    itemsRemove = itemsModule.remove;
    uploadSaveFile = requireBackendModule('modules/items/upload.service').saveFile;
    const categoriesModule = requireBackendModule('modules/categories/categories.service');
    categoriesFindAll = categoriesModule.findAll;
    categoriesFindOne = categoriesModule.findOne;
    categoriesCreate = categoriesModule.create;
    categoriesUpdate = categoriesModule.update;
    categoriesRemove = categoriesModule.remove;
    categoriesReorder = categoriesModule.reorder;
    const ordersModule = requireBackendModule('modules/orders/orders.service');
    ordersFindByTable = ordersModule.findByTable;
    ordersFindByHall = ordersModule.findByHall;
    ordersFindActiveOrders = ordersModule.findActiveOrders;
    ordersCreate = ordersModule.create;
    ordersUpdate = ordersModule.update;
    ordersUpdateStatus = ordersModule.updateStatus;
    ordersRemove = ordersModule.remove;
    const dineInModule = requireBackendModule('modules/orders/dine-in-orders.service');
    dineInOrdersCreate = dineInModule.create;
    dineInOrdersFindActive = dineInModule.findActive;
    dineInOrdersFindArchived = dineInModule.findArchived;
    dineInOrdersFindById = dineInModule.findById;
    dineInOrdersFindByTable = dineInModule.findByTable;
    dineInOrdersFindByHall = dineInModule.findByHall;
    dineInOrdersUpdate = dineInModule.update;
    dineInOrdersUpdateStatus = dineInModule.updateStatus;
    dineInOrdersMoveTableOrders = dineInModule.moveTableOrders;
    dineInOrdersMoveOrders = dineInModule.moveOrders;
    dineInOrdersSetTableGlobalDiscount = dineInModule.setTableGlobalDiscount;
    dineInOrdersRemoveAllArchived = dineInModule.removeAllArchived;
    const pickupModule = requireBackendModule('modules/orders/pickup-orders.service');
    pickupOrdersFindActive = pickupModule.findActive;
    pickupOrdersFindArchived = pickupModule.findArchived;
    pickupOrdersFindById = pickupModule.findById;
    pickupOrdersCreate = pickupModule.create;
    pickupOrdersUpdate = pickupModule.update;
    pickupOrdersUpdateStatus = pickupModule.updateStatus;
    pickupOrdersRemove = pickupModule.remove;
    pickupOrdersRemoveAllArchived = pickupModule.removeAllArchived;
    const deliveryModule = requireBackendModule('modules/orders/delivery-orders.service');
    deliveryOrdersFindActive = deliveryModule.findActive;
    deliveryOrdersFindArchived = deliveryModule.findArchived;
    deliveryOrdersFindById = deliveryModule.findById;
    deliveryOrdersCreate = deliveryModule.create;
    deliveryOrdersUpdate = deliveryModule.update;
    deliveryOrdersUpdateStatus = deliveryModule.updateStatus;
    deliveryOrdersRemove = deliveryModule.remove;
    deliveryOrdersRemoveAllArchived = deliveryModule.removeAllArchived;
    const deliveryPlatformsModule = requireBackendModule('modules/orders/delivery-platforms.service');
    deliveryPlatformsFindAll = deliveryPlatformsModule.findAll;
    deliveryPlatformsCreate = deliveryPlatformsModule.create;
    deliveryPlatformsUpdate = deliveryPlatformsModule.update;
    deliveryPlatformsRemove = deliveryPlatformsModule.remove;
    const tablesModule = requireBackendModule('modules/tables/tables.service');
    tablesFindAll = tablesModule.findAll;
    tablesFindByHall = tablesModule.findByHall;
    tablesFindOne = tablesModule.findOne;
    tablesCreate = tablesModule.create;
    tablesUpdate = tablesModule.update;
    tablesRemove = tablesModule.remove;
    const hallsModule = requireBackendModule('modules/halls/halls.service');
    hallsFindAll = hallsModule.findAll;
    hallsFindOne = hallsModule.findOne;
    hallsCreate = hallsModule.create;
    hallsUpdate = hallsModule.update;
    hallsRemove = hallsModule.remove;
    const floorsModule = requireBackendModule('modules/floors/floors.service');
    floorsFindAll = floorsModule.findAll;
    floorsFindOne = floorsModule.findOne;
    floorsCreate = floorsModule.create;
    floorsUpdate = floorsModule.update;
    floorsRemove = floorsModule.remove;
    const kitchensModule = requireBackendModule('modules/kitchens/kitchens.service');
    kitchensFindAll = kitchensModule.findAll;
    kitchensFindOne = kitchensModule.findOne;
    kitchensCreate = kitchensModule.create;
    kitchensUpdate = kitchensModule.update;
    kitchensRemove = kitchensModule.remove;
    const printersModule = requireBackendModule('modules/printers/printers.service');
    printersGetAllSettings = printersModule.getAllSettings;
    printersGetAvailablePrinters = printersModule.getAvailablePrinters;
    printersSaveSetting = printersModule.saveSetting;
    printersDeleteSetting = printersModule.deleteSetting;
    const offersModule = requireBackendModule('modules/offers/offers.service');
    offersCreateDailyDeal = offersModule.createDailyDeal;
    offersGetAllDailyDeals = offersModule.getAllDailyDeals;
    offersGetActiveDailyDeal = offersModule.getActiveDailyDeal;
    offersGetDailyDealByDate = offersModule.getDailyDealByDate;
    offersUpdateDailyDeal = offersModule.updateDailyDeal;
    offersDeleteDailyDeal = offersModule.deleteDailyDeal;
    offersCreateCombo = offersModule.createCombo;
    offersGetAllCombos = offersModule.getAllCombos;
    offersGetCombo = offersModule.getCombo;
    offersUpdateCombo = offersModule.updateCombo;
    offersDeleteCombo = offersModule.deleteCombo;
    offersCreateScheduledOffer = offersModule.createScheduledOffer;
    offersGetAllScheduledOffers = offersModule.getAllScheduledOffers;
    offersGetActiveScheduledOffers = offersModule.getActiveScheduledOffers;
    offersGetScheduledOffer = offersModule.getScheduledOffer;
    offersUpdateScheduledOffer = offersModule.updateScheduledOffer;
    offersDeleteScheduledOffer = offersModule.deleteScheduledOffer;
    offersSetFeatured = offersModule.setFeatured;
    offersGetAllFeaturedItems = offersModule.getAllFeaturedItems;
    offersIsFeatured = offersModule.isFeatured;
    offersCreateHappyHour = offersModule.createHappyHour;
    offersGetAllHappyHours = offersModule.getAllHappyHours;
    offersGetHappyHour = offersModule.getHappyHour;
    offersUpdateHappyHour = offersModule.updateHappyHour;
    offersDeleteHappyHour = offersModule.deleteHappyHour;
    offersGetEffectivePrice = offersModule.getEffectivePrice;
    offersEnrichItemsWithOffers = offersModule.enrichItemsWithOffers;
    const reportsModule = requireBackendModule('modules/reports/reports.service');
    getReportsDailySummary = reportsModule.getDailySummary;
    getReportsReportData = reportsModule.getReportData;
    generateReportsExcel = reportsModule.generateExcel;
    const shelvesModule = requireBackendModule('modules/shelves/shelves.service');
    shelvesFindAll = shelvesModule.findAll;
    shelvesFindOneById = shelvesModule.findOneById;
    shelvesFindOneByBarcode = shelvesModule.findOneByBarcode;
    shelvesCreate = shelvesModule.create;
    shelvesUpdate = shelvesModule.update;
    shelvesRemove = shelvesModule.remove;
    shelvesSell = shelvesModule.sell;
    const shiftsModule = requireBackendModule('modules/shifts/shifts.service');
    shiftsGetAllShifts = shiftsModule.getAllShifts;
    shiftsGetActiveShift = shiftsModule.getActiveShift;
    shiftsGetShiftById = shiftsModule.getShiftById;
    shiftsStartShift = shiftsModule.startShift;
    shiftsFinishShift = shiftsModule.finishShift;
    const financeModule = requireBackendModule('modules/finance/finance.service');
    financeGetRevenues = financeModule.getRevenues;
    financeCreateRevenue = financeModule.createRevenue;
    financeSyncRevenueFromOrders = financeModule.syncRevenueFromOrders;
    financeGetExpenses = financeModule.getExpenses;
    financeCreateExpense = financeModule.createExpense;
    financeUpdateExpense = financeModule.updateExpense;
    financeDeleteExpense = financeModule.deleteExpense;
    financeGetCashFlow = financeModule.getCashFlow;
    financeCreateCashFlow = financeModule.createCashFlow;
    financeSyncCashFlowFromOrders = financeModule.syncCashFlowFromOrders;
    financeGetProfitAndLoss = financeModule.getProfitAndLoss;
    const businessDayModule = requireBackendModule('modules/business-day/business-day.service');
    businessDayGetCurrentBusinessDay = businessDayModule.getCurrentBusinessDay;
    businessDayStartNewBusinessDay = businessDayModule.startNewBusinessDay;
    businessDayEnsureBusinessDayExists = businessDayModule.ensureBusinessDayExists;
    businessDayGetAllBusinessDays = businessDayModule.getAllBusinessDays;
    const settingsModule = requireBackendModule('modules/settings/settings.service');
    settingsGetShiftHours = settingsModule.getShiftHours;
    settingsUpdateShiftHours = settingsModule.updateShiftHours;
    const shiftDefsModule = requireBackendModule('modules/settings/shift-definitions.service');
    settingsGetShiftDefinitions = () => shiftDefsModule.getShiftDefinitions(false);
    settingsCreateShiftDefinition = shiftDefsModule.createShiftDefinition;
    settingsUpdateShiftDefinition = shiftDefsModule.updateShiftDefinition;
    settingsRemoveShiftDefinition = shiftDefsModule.removeShiftDefinition;
    settingsReplaceShiftDefinitions = shiftDefsModule.replaceShiftDefinitions;
    console.log('[MAIN] ✓ Backend modules loaded successfully');
  } catch (error: any) {
    console.error('[MAIN] ✗ Failed to load backend modules:', error);
    throw error;
  }
}

export async function initializeBackendLibrary(): Promise<boolean> {
  console.log('[BACKEND] Initializing backend as library...');

  try {
    const userDataPath = app.getPath('userData');
    console.log('[BACKEND] User data path:', userDataPath);

    console.log('[BACKEND] Calling initializeBackend()...');
    const backendAppInstance = await initializeBackend(userDataPath);
    console.log('[BACKEND] initializeBackend() completed');

    if (!backendAppInstance) {
      throw new Error('initializeBackend() returned null or undefined');
    }

    setBackendApp(backendAppInstance);
    console.log('[BACKEND] ✓ Backend initialized as library');
    return true;
  } catch (error: any) {
    console.error('[BACKEND] ✗✗✗ FAILED TO INITIALIZE BACKEND ✗✗✗');
    console.error('[BACKEND] Error:', error);
    console.error('[BACKEND] Message:', error?.message);

    const errorDetails = [
      `Error: ${error?.message || String(error)}`,
      `Type: ${error?.constructor?.name || 'Unknown'}`,
      '',
      'Check logs at:',
      app.getPath('userData'),
      '',
      'Full error:',
      error?.stack || String(error),
    ].join('\n');

    try {
      dialog.showErrorBox('Backend Initialization Failed', errorDetails);
    } catch (e) {
      console.error('[BACKEND] Failed to show error dialog:', e);
    }

    return false;
  }
}
