export {
  initializeTables,
  requireTables,
  findAll,
  findByHall,
  findOne,
  create,
  update,
  remove,
  isTableUnlocked,
  unlockTable,
  lockTable,
  getCustomerLockedTable,
  lockCustomerToTable,
  unlockCustomerFromTable,
  TablesService,
  type TableEntity,
} from './tables.service';
