/**
 * Sample payloads for printer settings preview / test print.
 */
export const KITCHEN_TEST_PRINT_DATA = {
  orderId: 80,
  table: 4,
  hall: 'صالة 4',
  floor: 'طابق 1',
  waiter: 'أحمد',
  cashier: 'سارة',
  items: [
    {
      id: 10,
      item_name: 'صينية 1',
      quantity: 1,
      price: 0,
      is_tray_header: true,
      tray_number: 1,
    },
    {
      id: 11,
      item_name: 'كريب سادة',
      quantity: 2,
      price: 0,
      is_tray_child: true,
      tray_number: 1,
    },
    {
      id: 12,
      item_name: 'بانكيك',
      quantity: 2,
      price: 0,
      is_tray_child: true,
      tray_number: 1,
    },
    {
      id: 13,
      item_name: 'فرنسي',
      quantity: 1,
      price: 0,
      is_tray_child: true,
      tray_number: 1,
    },
    {
      id: 20,
      item_name: 'صينية 2',
      quantity: 2,
      price: 0,
      is_tray_header: true,
      tray_number: 2,
    },
    {
      id: 21,
      item_name: 'كريب نوتيلا',
      quantity: 2,
      price: 0,
      is_tray_child: true,
      tray_number: 2,
    },
    {
      id: 22,
      item_name: 'بانكيك',
      quantity: 4,
      price: 0,
      is_tray_child: true,
      tray_number: 2,
    },
    {
      id: 2,
      item_name: 'وافل بالنوتيلا',
      quantity: 1,
      price: 0,
      service_type: 'dine-in' as const,
    },
    {
      id: 3,
      item_name: 'بانكيك',
      quantity: 1,
      price: 0,
      service_type: 'dine-in' as const,
    },
  ],
  totals: { total: 5000 },
  timestamp: new Date().toISOString(),
  restaurantName: 'سفرة',
  kitchenName: 'مطبخ الحلويات',
  note: 'بدون سكر إضافي',
  service_type: 'dine-in' as const,
  reprintCount: 0,
};

export const CUSTOMER_TEST_RECEIPT_DATA = {
  orderId: 999,
  invoiceNumber: 'INV-999',
  table: 5,
  hall: 'الصالة الرئيسية',
  floor: 'الطابق الأول',
  waiter: 'أحمد',
  cashier: 'سارة',
  address: 'بغداد — الكرادة، شارع أبو نواس',
  phone: '0770 000 0000',
  taxNumber: 'TAX-12345',
  website: 'www.sufra.iq',
  thankYouMessage: 'شكراً لزيارتكم — نتطلع لرؤيتكم مجدداً',
  items: [
    {
      order_id: 999,
      item_name: 'صينية 1',
      quantity: 1,
      price: 21500,
      discount: 0,
      service_type: 'dine-in' as const,
      is_tray_header: true,
      tray_number: 1,
    },
    {
      order_id: 999,
      item_name: 'سونلاج',
      quantity: 1,
      price: 8000,
      service_type: 'dine-in' as const,
      is_tray_child: true,
      tray_number: 1,
    },
    {
      order_id: 999,
      item_name: 'كريب سادة',
      quantity: 1,
      price: 3500,
      service_type: 'dine-in' as const,
      is_tray_child: true,
      tray_number: 1,
    },
    {
      order_id: 999,
      item_name: 'وافل بالنوتيلا',
      quantity: 1,
      price: 3500,
      discount: 0,
      service_type: 'dine-in' as const,
    },
    {
      order_id: 999,
      item_name: 'مشروب',
      quantity: 2,
      price: 2500,
      discount: 500,
      service_type: 'dine-in' as const,
    },
  ],
  totals: {
    subtotal: 30000,
    globalDiscount: { percent: 10, amount: 3000 },
    tax: 0,
    serviceCharge: 0,
    total: 27000,
  },
  timestamp: new Date().toISOString(),
  restaurantName: 'سفرة',
  paymentMethod: 'نقد',
  paidAmount: 15000,
  change: 1500,
  remaining: 0,
  service_type: 'dine-in' as const,
};

export function kitchenTestPrintData(kitchenName?: string) {
  return {
    ...KITCHEN_TEST_PRINT_DATA,
    timestamp: new Date().toISOString(),
    printTime: new Date().toISOString(),
    kitchenName: kitchenName || 'المطبخ',
  };
}

export function customerTestReceiptData() {
  return {
    ...CUSTOMER_TEST_RECEIPT_DATA,
    timestamp: new Date().toISOString(),
  };
}
